import reference from "./mimic-reference.json";

export interface DocumentationTopic {
  id: string;
  title: string;
  description: string;
  path: string;
  category: string;
  keywords: string[];
  hub?: boolean;
}

export const documentationCategories = [
  { id: "start", label: "Get started" },
  { id: "configure", label: "Configure" },
  { id: "reference", label: "Reference" },
  { id: "diagnose", label: "Troubleshoot" },
  { id: "optimize", label: "Optimize" },
];

export const documentationTopics: DocumentationTopic[] = [
  {
    id: "demo",
    title: "Run your first demo",
    description:
      "Choose your language and client. Install, run, and see Example Domain.",
    path: "sdk/#sdk-explorer",
    category: "start",
    keywords: [
      "install",
      "launch",
      "connect",
      "C#",
      "dotnet",
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "Kotlin",
      "Go",
      "Rust",
      "Ruby",
      "PHP",
      "Playwright",
      "Puppeteer",
      "Rod",
      "chromedp",
      "Ferrum",
      "chromiumoxide",
    ],
  },
  {
    id: "sdk",
    title: "Using the SDK",
    description:
      "Learn how sessions, native browser objects and Mimic options fit together.",
    path: "docs/sdk/",
    category: "start",
    keywords: [
      "browser",
      "page",
      "locator",
      "API",
      "framework",
      "session",
      "newContext",
    ],
  },
  {
    id: "direct-cdp",
    title: "Connect directly over CDP",
    description:
      "Manage the process yourself and attach your existing browser client.",
    path: "docs/connect/",
    category: "start",
    keywords: [
      "endpoint",
      "WebSocket",
      "9222",
      "connectOverCDP",
      "browserURL",
      "raw",
      "headless",
    ],
  },
  {
    id: "runtime",
    title: "Runtime & installation",
    description:
      "Choose a runtime version, reuse the cache and prepare offline environments.",
    path: "docs/sdk/runtime/",
    category: "configure",
    keywords: [
      "download",
      "runtimeVersion",
      "runtime_version",
      "pin",
      "timeout",
      "engine",
      "runtimeDir",
      "cache",
      "offline",
      "executable",
      "MIMIC",
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "NO_PROXY",
    ],
  },
  {
    id: "contexts",
    title: "Contexts & configuration",
    description:
      "Isolate sessions, configure coherent profiles and keep native options familiar.",
    path: "docs/sdk/contexts/",
    category: "configure",
    keywords: [
      "newContext",
      "new_context",
      "profile",
      "proxy",
      "resourcePolicy",
      "media",
      "framework",
      "ownership",
      "cookies",
      "storage",
      "viewport",
      "locale",
      "timezone",
      "fingerprint",
    ],
  },
  {
    id: "profiles",
    title: "Environment profiles",
    description:
      "Understand browser identity, profile fields and their coherence rules.",
    path: "docs/profiles/",
    category: "configure",
    keywords: [
      "generateProfile",
      "exportProfile",
      "importProfile",
      "userAgent",
      "screen",
      "permissions",
      "capabilities",
      "timing",
      "navigator",
      "seed",
    ],
  },
  {
    id: "media",
    title: "Camera & microphone",
    description:
      "Choose capture sources and control the device identities a site observes.",
    path: "docs/sdk/media/",
    category: "configure",
    keywords: [
      "OBS",
      "camera",
      "microphone",
      "audio",
      "video",
      "getUserMedia",
      "sourceId",
      "devices",
      "defaultMode",
      "frameRate",
      "permissions",
      "capture",
      "WebRTC",
    ],
  },
  {
    id: "api",
    title: "API reference",
    description:
      "Look up Mimic commands, parameters, results, scope and support boundaries.",
    path: "docs/sdk/reference/",
    category: "reference",
    keywords: [
      "Mimic",
      "command",
      "typed",
      "params",
      "result",
      "session.mimic",
      "forPage",
      "error",
      "experimental",
      "ProtocolError",
    ],
  },
  {
    id: "cli",
    title: "Command-line reference",
    description:
      "Start the executable, choose its engine and configure its CDP listener.",
    path: "docs/cli/",
    category: "reference",
    keywords: [
      "--listen",
      "--chrome",
      "--engine",
      "--browser-mode",
      "--navigation-timeout",
      "--profile",
      "--dev-preview",
      "flags",
      "headless",
    ],
  },
  {
    id: "compatibility",
    title: "Compatibility & support",
    description:
      "Understand workload fit, supported behavior and what needs a full browser.",
    path: "docs/compatibility/",
    category: "diagnose",
    keywords: [
      "unsupported",
      "screenshot",
      "PDF",
      "CSS",
      "layout",
      "security",
      "sandbox",
      "FAQ",
      "license",
      "Chrome",
    ],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    description:
      "Resolve connection failures, wait for application readiness and inspect unsupported commands.",
    path: "docs/troubleshooting/",
    category: "diagnose",
    keywords: [
      "connection",
      "loading",
      "hydration",
      "selector",
      "ready",
      "fonts",
      "diagnostic",
      "timeout",
      "download",
      "error",
    ],
  },
  {
    id: "optimize",
    title: "Optimize a workload",
    description:
      "Measure the workload, try changes and keep only the result your assertions accept.",
    path: "docs/optimize/",
    category: "optimize",
    keywords: [
      "performance",
      "memory",
      "policy",
      "report",
      "record",
      "replay",
      "profile",
      "speed",
    ],
  },
  {
    id: "workloads",
    title: "Workload setup",
    description:
      "Connect your script to the managed runtime and define what success means.",
    path: "docs/optimize/workloads/",
    category: "optimize",
    keywords: ["MIMIC_CDP_URL", "assertions", "scraper", "optimize", "runner"],
  },
  {
    id: "saved-profiles",
    title: "Save and reuse optimization",
    description:
      "Run the same workload with a selected, validated workload profile.",
    path: "docs/optimize/profiles/",
    category: "optimize",
    keywords: ["workload", "export", "save", "reuse", "--profile"],
  },
  {
    id: "replay",
    title: "Record & replay",
    description: "Reuse captured requests when comparing workload behavior.",
    path: "docs/optimize/replay/",
    category: "optimize",
    keywords: ["recording", "offline", "network", "capture", "replay"],
  },
  {
    id: "optimization-safety",
    title: "Optimization safety",
    description: "Review the boundaries before applying resource changes.",
    path: "docs/optimize/safety/",
    category: "optimize",
    keywords: [
      "correctness",
      "validation",
      "assertions",
      "limits",
      "reportOnly",
    ],
  },
  {
    id: "versions",
    title: "Pin a runtime version",
    description:
      "Select an exact runtime without changing your SDK package version.",
    path: "docs/sdk/runtime/#versions",
    category: "configure",
    keywords: [
      "runtimeVersion",
      "runtime_version",
      "version",
      "pin",
      "latest",
      "release",
    ],
    hub: false,
  },
  {
    id: "cache",
    title: "Runtime cache",
    description:
      "Find the shared cache, choose its directory and manage installed releases.",
    path: "docs/sdk/runtime/#cache",
    category: "configure",
    keywords: [
      "MIMIC_RUNTIME_DIR",
      "LOCALAPPDATA",
      "XDG_CACHE_HOME",
      "home",
      "cache",
      "prune",
    ],
    hub: false,
  },
  {
    id: "offline",
    title: "Offline installation",
    description:
      "Prepare a verified runtime before disabling runtime downloads.",
    path: "docs/sdk/runtime/#offline",
    category: "configure",
    keywords: [
      "MIMIC_DOWNLOAD",
      "allowDownload",
      "lock",
      "archive",
      "checksum",
      "install",
    ],
    hub: false,
  },
  {
    id: "custom-executable",
    title: "Use your own executable",
    description:
      "Override automatic acquisition when you manage a runtime build yourself.",
    path: "docs/sdk/runtime/#executable",
    category: "configure",
    keywords: [
      "MIMIC_EXECUTABLE_PATH",
      "executablePath",
      "executable_path",
      "local binary",
    ],
    hub: false,
  },
  {
    id: "runtime-options",
    title: "Runtime options by language",
    description: "Find the exact option names and timeout units for your SDK.",
    path: "docs/sdk/runtime/#options",
    category: "reference",
    keywords: [
      "RuntimeOptions",
      "options",
      "timeout",
      "startup_timeout",
      "lock_timeout",
      "engine",
      "cancellation",
    ],
    hub: false,
  },
  {
    id: "save-profile",
    title: "Save & restore a browser profile",
    description:
      "Export a profile token, store it and reuse the same coherent environment.",
    path: "docs/sdk/contexts/#save-profile",
    category: "configure",
    keywords: ["seed", "import", "export", "profile", "identity"],
    hub: false,
  },
  {
    id: "proxy",
    title: "Context proxies",
    description:
      "Route browser requests through a selected proxy independently of SDK downloads.",
    path: "docs/sdk/contexts/#proxies",
    category: "configure",
    keywords: [
      "SOCKS",
      "SOCKS5",
      "HTTP",
      "username",
      "password",
      "proxy",
      "server",
    ],
    hub: false,
  },
  {
    id: "resources",
    title: "Resource policies",
    description:
      "Set request rules, presets and budgets, or observe them with reportOnly.",
    path: "docs/sdk/contexts/#resource-policy",
    category: "configure",
    keywords: [
      "resourcePolicy",
      "resource_policy",
      "rules",
      "budgets",
      "maxRequests",
      "maxConcurrent",
      "presets",
      "maxBytes",
      "reportOnly",
      "block",
    ],
    hub: false,
  },
  {
    id: "ownership",
    title: "Session ownership & cleanup",
    description:
      "Close an owned runtime or disconnect from a runtime managed elsewhere.",
    path: "docs/sdk/runtime/#ownership",
    category: "reference",
    keywords: [
      "close",
      "dispose",
      "connect",
      "launch",
      "context",
      "cleanup",
      "lifecycle",
    ],
    hub: false,
  },
];

documentationTopics.push(
  {
    id: "manual-workload-policy",
    title: "Manual optimization controls",
    description:
      "Set a workload resource policy deliberately and validate it with your assertions.",
    path: "docs/optimize/manual-policy/",
    category: "optimize",
    keywords: [
      "manual",
      "policy",
      "resource",
      "allow",
      "block",
      "optimize",
      "controls",
    ],
  },
  {
    id: "optimization-errors",
    title: "Troubleshoot optimization",
    description:
      "Diagnose rejected training, capture and replay failures before reusing a profile.",
    path: "docs/optimize/troubleshooting/",
    category: "optimize",
    keywords: [
      "training",
      "failure",
      "replay",
      "capture",
      "timeout",
      "troubleshooting",
      "optimize",
    ],
  },
  {
    id: "optimization-methodology",
    title: "Optimization benchmarks",
    description:
      "Understand how workload improvements are measured and compared.",
    path: "docs/optimize/benchmarks/",
    category: "optimize",
    keywords: [
      "benchmark",
      "measurement",
      "methodology",
      "memory",
      "latency",
      "performance",
      "optimize",
    ],
  },
  {
    id: "optimization-results",
    title: "Measured optimization results",
    description:
      "Read workload measurements and the boundaries that affect their interpretation.",
    path: "docs/optimize/results/",
    category: "optimize",
    keywords: [
      "dynamic",
      "results",
      "throughput",
      "memory",
      "performance",
      "optimize",
    ],
  },
);

// Command metadata stays small; full types and examples load only on the reference route.
documentationTopics.push(
  ...reference.commands.map((command) => ({
    id: `api-${command.id}`,
    title: command.name,
    description: command.description,
    path: `docs/sdk/reference/#${command.id}`,
    category: "reference",
    keywords: [
      command.name,
      command.scope,
      command.status,
      ...command.params.fields.map((field) => field.name),
      ...command.result.fields.map((field) => field.name),
    ],
    hub: false,
  })),
);
